### ISSUE TITLE
Setting temporary locations

### ISSUE THREAD

**Issue by ojraab** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#10]
Hello,
I'm trying to use ItemUpdater to change the temporary location of items. I can change the value of the temporary location code itself using **temp_library** + **temp_location**, but if I include **in_temp_location** the Updater returns the following error:
"Error: can't assign to property "value" on false: not an object "
I'm using a column header of 'in_temp_location' with a value of 'true' (also tried 'TRUE' and 'T'). 

**in_temp_location** is the correct element name according to the rest_item.xsd, so can you please tell me why I'm getting this error?

**Comment by ori229** [comment]
We had a bug with boolean fields. Fixed now.
Please try with in_temp_location and true/false.
