### ISSUE TITLE
Inventory date format

### ISSUE THREAD

**Issue by Anchi77** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#11]
Hi Support,
We try to use this function to update the "inventory date," but we don't know what the correct format is.

We used 20180812 to upload it, but it displays 01/01/20180812.

We also try to use 
2018/08/12
2018-08-12
2018.08.12

But display Error:
2018/08/12 (through reference chain: com.exlibris.alma.ws.jaxb.item.Item["item_data"]->com.exlibris.alma.ws.jaxb.item.ItemData["inventory_date"]) (SUST0000192053)

Only 20180812 can successfully upload into Alma.
Can you please let me know what is the correct format with "date"?

Many thanks,
Anchi

**Comment by ori229** [comment]
Please try with 2018-08-12Z 
(Same syntax as used with Alma's APIs. The "Z" means Zero offset from UTC)

**Comment by ori229** [comment]
.
