### ISSUE TITLE
Problem with invalid values

### ISSUE THREAD

**Issue by ojraab** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#12]
Hello,
We are trying to use the Item Updater to change temporary locations on batches of items. We've encounter some errors related to records that have invalid values in other fields unrelated to what we are doing. Specifically, the physical_material_type field and the pattern_type fields. In the case of the material type, we are going to use the item information update to correct the invalid values, but we cannot easily search for and identify invalid values in the pattern_type (related to the predictive pattern defined in the holding record). Is there a way that this type of error can be overlooked by the Item Updater? Perhaps is can be reported but allow the requested changes to be applied?

Thanks,
Oscar Raab

**Comment by ori229** [comment]
This is a limitation of the API, and not of the Cloud App. The invalid values source is known?
