### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by jkarlsen** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#13]
I was going to suggest that support for CSV be added, since I have a use case where CSV was needed. But I tried it and found that it already works. So I would suggest updating the documentation to say which file formats are supported (I don't know if e.g. tab-separated is also supported).

**Comment by ori229** [comment]
Updated (https://developers.exlibrisgroup.com/appcenter/item-updater-by-excel/ )
