### ISSUE TITLE
Error when moving items to temporary location: Unrecognized field due_back_date

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#15]
Hi,

When moving items to a temporary location, I get an error if I include the due_back_date: "Unrecognized field "due_back_date". This is the data I'm using:
![image](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/assets/76584888/ee050c9e-d993-4adb-a0a1-b782b7cd1c4c)

Is this field not available for update or is the data in the Excel file wrongly formatted? I have tried changing the date format but to no avail. If I remove the due_back_date column the item is updated.

Regards,

Helgi

**Comment by ori229** [comment]
Resolved: https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/commit/693c80a26141d6e7d969e86a6125bf9a4c8242ae
