### ISSUE TITLE
Error: No lookup key after v0.09 release?

### ISSUE THREAD

**Issue by grimmerryan** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#17]
Since the latest release of v0.09, I'm getting an error of no lookup key when using the barcode for the items to be updated. I've tried uninstalling and reactivating the cloud app and loading Excel files that had previously loaded successfully, and I am still receiving the above error.

**Comment by ori229** [comment]
Fixed https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/releases/tag/v0.1.0
