### ISSUE TITLE
Add field "item_call_number"

### ISSUE THREAD

**Issue by 4x7152** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#18]
Hi there

Could you add field "item_call_number" so it'll be possible to edit it in batch? If I upload an Excel file with top column "item_call_number" I get the following error message:
Unrecognized field "item_call_number" (class com.exlibris.alma.ws.jaxb.item.ItemData), not marked as ignorable (76 known properties: "barcode", "retention_reason", "public_note", "imprint", "process_type", "pid", "inventory_number", "creation_date", "due_date_policy", "due_date", "base_status", "provenance", "receiving_operator", "receive_number", "inventory_price", "alt_call_no", "inventory_date", "policy", "year_of_issue", "po_line", "location", "alternative_call_number", "library", "edition", "linking_number", "statistics_note_2", "chronology_i", "chronology_j", "pages", "pieces", "chronology_m", "break_indicator", "issue_date", "language", "replacement_cost", "expected_arrival_date", "alternative_call_number_type", "internal_note_1", "type_of_unit", "internal_note_3", "enumeration_a", "physical_material_type", "enumeration_c", "enumeration_d", "enumeration_e", "requested", "enumeration_g", "enumeration_h", "modification_date", "weeding_number", "is_magnetic", "description", "pattern_type", "title_abcnph", "storage_location_id", "work_order_at", "arrival_date", "alt_number_source", "library_details" [truncated]])

Thanks!

Best
Sarah

**Comment by ori229** [comment]
Try alternative_call_number

**Comment by 4x7152** [comment]
I did, thanks  :)

Von: ori229 ***@***.***>
Gesendet: Donnerstag, 15. Februar 2024 16:07
An: ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel ***@***.***>
Cc: Hartmann Sarah ***@***.***>; State change ***@***.***>
Betreff: Re: [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel] Add field "item_call_number" (Issue #18)


Try alternative_call_number

-
