### ISSUE TITLE
How to use holding ID to change the location?

### ISSUE THREAD

**Issue by Anchi77** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#19]
Hi Support,

Can we use a holding ID to change the item's holding?

For example,
Under this bib record you can see here have two holdings:
![image](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/assets/129164740/105a80cb-f2f7-43c8-9f16-95d774f31068)
Actually, they are the same holding, but the call numbers are different, so Alma set it to a different holding (with a different holding_id). 
it caused we can't use job to batch-change the holding.

I try to use this app to mapping item to correct holding:
![image](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/assets/129164740/1c72cae6-7677-4a30-a3f9-f24d0cbe9d38)
but failed, and nothing happened.

Please help to check if there is any way to batch assigned items to the correct holding.

Many thanks and best regards,
Anchi

**Comment by ori229** [comment]
This Cloud App cannot move an item from one holding to another. Perhaps you can just update the item's call-number based on its barcode?

**Comment by Anchi77** [comment]
Hi Ori,
Thanks for your reply, i understand we cannot use this app to change the holding.

Thank you! Anchi
