### ISSUE TITLE
This cloud app does not work at all

### ISSUE THREAD

**Issue by HXyL229ZI0gk5u** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#2]
I tried using this cloud app with the most simple test file containing only one row, but it just returned an error message about 'unrecognized field "key"' -- although the first row used one of the properties listed in the error message.
[test2.xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/9945320/test2.xlsx)

**Comment by ori229** [comment]
From the input file I see you tried with replacement_cost
Can you try with a different field, such as "description"? Perhaps it's a problem specifically with replacement_cost

**Comment by HXyL229ZI0gk5u** [comment]
Yes, changing replacement_cost to description successfully updated the item
record without any error message. Likewise, changing it to enumeration_a
also worked, for another instance.

**Comment by ori229** [comment]
Thanks.  We'll check why replacement_cost doesn't work. Maybe because it's a numeric field.

**Comment by ori229** [comment]
Fixed witrh https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/releases/tag/v0.0.3
