### ISSUE TITLE
Update item and popup error message

### ISSUE THREAD

**Issue by Anchi77** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#20]
Hi Support,

We have 232 items that failed to update, it will pop up the error message:
Error: Request failed: Invalid temp_location code: themed (30101000164947)
![image](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/assets/129164740/180776db-e71e-49a3-b834-caeeb99a6a80)

Please see the attachment "item updater 0403" which is our upload file.
[item updater 0403.xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/14848523/item.updater.0403.xlsx)

Please help to check how to fix it, many thanks.
Anchi

**Comment by ori229** [comment]
The Cloud App retrieves an item using a GET request, modifies the output (only the fields mentioned in the Excel file), and sends a PUT request with all the fields. 
Seems like all the items on your list have illegal data. Can you try to fix one manually (using the UI) and retry?
You can also add another column to the Excel (temp_location) to fix it for all of them.

**Comment by Anchi77** [comment]
Thank you for your prompt reply!
