### ISSUE TITLE
Some fields not being added to item record when present in file (and no error displays)

### ISSUE THREAD

**Issue by selamarin** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#21]
The following fields are not being added to items because the script 'cloudapp/src/app/main/item.service.ts' is nesting them under the 'item_data' element instead of the 'holding_data' element in the json:

- copy_id
- in_temp_location
- temp_library
- temp_location
- temp_call_number_type
- temp_call_number
- temp_call_number_source
- temp_policy
- due_back_date

These fields would be incredibly beneficial to be able to add with this cloudapp. See lines 55-65 in 'cloudapp/src/app/main/item.service.ts' that need to be reworked.

Thanks!

**Comment by aschri1** [comment]
Can't confirm if this is the same cause but in addition to the above fields, description is also no longer being updated by the app.

**Comment by ori229** [comment]
Testing with the attached Excel, it worked with all the "temporary X" fields.  "Description" works as well.  Can you double-check?


[Book1.xlsx](https://github.com/user-attachments/files/18095864/Book1.xlsx)

**Comment by selamarin** [comment]
It still doesn't add any of the temporary fields. We haven't had an issue with description at Getty, just temp fields. 
![temp_location](https://github.com/user-attachments/assets/438e3f45-2f54-49b2-ba6f-1e188d7ef411)

The issue shouldn't be with the spreadsheet or the headers -- it's because the code is trying to add these headers nested under 'item' instead of 'holding'.

**Comment by selamarin** [comment]
Apologies! It's working in this app, but not in the Creator app! I will move this bug report to the other cloud app.
