### ISSUE TITLE
Item updater by Excel - which fields can be updated?

### ISSUE THREAD

**Issue by IrenaSivakova** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#3]
Hi, 
I would like to know which fields in Alma can be updated by using the cloud app "Item updater by Excel"? I looked at the Developer network site (https://developers.exlibrisgroup.com/appcenter/item-updater-by-excel/) and also into the help of the application but I didn't find any list of fields which can be updated. Could you give me more information please? 
Kind regards, 
Irena

**Comment by ori229** [comment]
In the Alma Item XSD doc: https://developers.exlibrisgroup.com/alma/apis/xsd/rest_item.xsd/?tags=PUT
any field under the holding_data and the item_data can be updated.
