### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by HXyL229ZI0gk5u** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#5]
The circle just keeps spinning when I try to upload Excel spreadsheets for testing. I have tried Chrome, Firefox, and Edge, all without success. The simple test file used is attached.
[test.xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/10024209/test.xlsx)

**Comment by ori229** [comment]
Fixed: https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/releases/tag/v0.0.5

**Comment by barthollingsworth** [comment]
Same problem as was reported Nov 16 2022.   tried different browsers etc., keeps spinning....  oddly it works occassionally.   Not sure what fix is indicated in the link   https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/releases/tag/v0.0.5  i downloaded each to no effect.   I am trying first 300 records, then 270, then 30, then 10 and it keeps spinning
[Rock Storage Theses_30_270_from was the 300 but removed.xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/13675818/Rock.Storage.Theses_30_270_from.was.the.300.but.removed.xlsx)
