### ISSUE TITLE
Issues Deleting Values with Item Updater

### ISSUE THREAD

**Issue by pyangucd** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#6]
I wanted to run an update where values in Enum C and Chron K are deleted. I've added the fields I wanted deleted as a column and left them blank but the update does not delete those fields. Please see image for reference to sample of columns.

![Capture](https://user-images.githubusercontent.com/118858477/203433582-7a8e6aab-18df-4304-811b-f088fa5b9b6b.JPG)

**Comment by ori229** [comment]
Fixed: https://github.com/exlibrisgroup/hep-cloudapp-itemupdater-excel/releases/tag/v0.0.6
