### ISSUE TITLE
User authorization error

### ISSUE THREAD

**Issue by straill** [ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel#7]
A staff user with the roles in the attached spreadsheet can see and activate the app, but gets the error message "You are not authorized to perform the requested action" upon clicking Load Items.  
[rolesList.xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/10282216/rolesList.xlsx)

I am able to successfully update items with the app, using the same spreadsheet as the staff user. I have many more Alma roles (including most administrator roles). See attached for my roles:
[rolesList (1).xlsx](https://github.com/ExLibrisGroup/hep-CloudApp-ItemUpdater-Excel/files/10282247/rolesList.1.xlsx)

Why does the staff user get this error? We assume this is role based, having eliminated other explanations.

**Comment by ori229** [comment]
The issue here was on Alma's side. When calling the Get-item-by-barcode API from within a Cloud App, the privilege needed for the API was too restrictive. It will be set to PHYSICAL_INVENTORY_VIEW starting March Release.
